Updates to documentation to for Go, PHP, Python for get and capture t…
gr4vy/gr4vy-docs pull request #49
Opened 2021-11-15 13:28 UTC by phillipgr4vy

…ransaction examples

2021-11-16 12:17 UTC, cbetta commented on docs/web-checkout/inspect.mdx
> + <TabItem value ="go">
```suggestion
 <TabItem value="go">
```

2021-11-16 12:17 UTC, cbetta commented on docs/web-checkout/inspect.mdx
> + <TabItem value ="php">
```suggestion
 <TabItem value="php">
```

2021-11-16 12:18 UTC, cbetta commented on versioned_docs/version-1.0.0/web-checkout/inspect.mdx
> + <TabItem value ="go">
```suggestion
 <TabItem value="go">
```

2021-11-16 12:18 UTC, cbetta commented on versioned_docs/version-1.1.0/web-checkout/inspect.mdx
> + <TabItem value ="php">
```suggestion
 <TabItem value="php">
```

2021-11-16 12:18 UTC, cbetta commented on versioned_docs/version-1.1.0/web-checkout/inspect.mdx
> + <TabItem value ="go">
```suggestion
 <TabItem value="go">
```

2021-11-16 12:19 UTC, cbetta requested changes
I like it. Happy to merge with the requested changes. 

Just 1 question: Is this a good order for the code samples? Node, cURL, Go, PHP, Python? What would be the most used ones? Maybe put those first?

2021-11-17 09:38 UTC, steve-gr4vy approved these changes
Looks good.

2021-11-18 14:14 UTC, cbetta approved these changes

2021-11-18 14:15 UTC, merged